### PR TITLE
Add support for multiple locations. And a unit test.

### PR DESCRIPTION
**Pull request by a-out-10-2**
This commit addresses Issue #7.

### CODE REVIEW

**Comment by a-out-10-2** [comment]
Unit tests have ran with Python 2 and 3. All have passed.

**Comment by alastair** [comment]
nice, thanks! I'm on vacation at the moment, will look at it in September

**Comment by mxjeff** [comment]
ping? Any progress with that PR?

**Comment by alastair** [comment]
A belated thanks for the patch, and the reminder to merge it! It's been so long since I worked on this I'm glad to see that other people are getting value out of it!!

**Pull request merged**
